// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahDP-hOcWkb3zadG3t1lkPOkcrBKwztE',
    appId: '1:431808372174:web:cce954a95c82dbc10c1f9f',
    messagingSenderId: '431808372174',
    projectId: 'notificationchat-d2d49',
    authDomain: 'notificationchat-d2d49.firebaseapp.com',
    storageBucket: 'notificationchat-d2d49.appspot.com',
    measurementId: 'G-D6QX0HE66P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTq5_JRwwILFtspN_mzk9_E8Y1vK5S4Y',
    appId: '1:431808372174:android:309049597f4db3650c1f9f',
    messagingSenderId: '431808372174',
    projectId: 'notificationchat-d2d49',
    storageBucket: 'notificationchat-d2d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiIcTsb44lvBNT8jCYBrx2OcaleiKPLtk',
    appId: '1:431808372174:ios:1746c5a96c2a00760c1f9f',
    messagingSenderId: '431808372174',
    projectId: 'notificationchat-d2d49',
    storageBucket: 'notificationchat-d2d49.appspot.com',
    iosBundleId: 'com.example.tqniaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiIcTsb44lvBNT8jCYBrx2OcaleiKPLtk',
    appId: '1:431808372174:ios:ad82513647c24d7c0c1f9f',
    messagingSenderId: '431808372174',
    projectId: 'notificationchat-d2d49',
    storageBucket: 'notificationchat-d2d49.appspot.com',
    iosBundleId: 'com.example.tqniaChat.RunnerTests',
  );
}
